import type { Product } from "./types";

export const products: Product[] = [
    {
        name: "ail",
        months: ["Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 149,
        macros: {
            lipides: 0.5,
            acidesGrasSatures: 0.1,
            glucides: 33.1,
            sucres: 1,
            proteines: 6.36,
        },
    },
    {
        name: "ananas",
        months: ["Janvier", "Février", "Mars", "Novembre", "Décembre"],
        kcal: 50,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 13,
            sucres: 10,
            proteines: 0.5,
        },
    },
    {
        name: "avocat",
        months: ["Janvier", "Février", "Mars", "Avril", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 160,
        macros: {
            lipides: 15,
            acidesGrasSatures: 2.1,
            glucides: 9,
            sucres: 0.7,
            proteines: 2,
        },
    },
    {
        name: "betterave",
        months: ["Janvier", "Février", "Mars", "Octobre", "Novembre", "Décembre"],
        kcal: 43,
        macros: {
            lipides: 0.17,
            acidesGrasSatures: 0,
            glucides: 9.56,
            sucres: 6.76,
            proteines: 1.61,
        },
    },
    {
        name: "blette",
        months: ["Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre"],
        kcal: 19,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 3.7,
            sucres: 1.1,
            proteines: 1.8,
        },
    },
    {
        name: "brocoli",
        months: ["Septembre", "Octobre", "Novembre"],
        kcal: 34,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0,
            glucides: 7,
            sucres: 1.7,
            proteines: 2.8,
        },
    },
    {
        name: "carotte",
        months: ["Janvier", "Février", "Mars", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 41,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 10,
            sucres: 4.7,
            proteines: 0.9,
        },
    },
    {
        name: "cèpe",
        months: ["Octobre", "Novembre", "Décembre"],
        kcal: 32,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0,
            glucides: 3,
            sucres: 1.7,
            proteines: 3.1,
        },
    },
    {
        name: "céleri",
        months: ["Janvier", "Février", "Mars", "Octobre", "Novembre", "Décembre"],
        kcal: 14,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 3,
            sucres: 1.3,
            proteines: 0.7,
        },
    },
    {
        name: "chou",
        months: ["Janvier", "Février", "Mars", "Octobre", "Novembre", "Décembre"],
        kcal: 25,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 6,
            sucres: 3.2,
            proteines: 1.3,
        },
    },
    {
        name: "chou chinois",
        months: ["Octobre", "Novembre", "Décembre"],
        kcal: 12,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 2.2,
            sucres: 0,
            proteines: 1.1,
        },
    },
    {
        name: "chou de bruxelles",
        months: ["Janvier", "Février", "Mars", "Octobre", "Novembre", "Décembre"],
        kcal: 43,
        macros: {
            lipides: 0.3,
            acidesGrasSatures: 0.1,
            glucides: 9,
            sucres: 2.2,
            proteines: 3.4,
        },
    },
    {
        name: "chou-fleur",
        months: ["Janvier", "Février", "Mars", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 25,
        macros: {
            lipides: 0.3,
            acidesGrasSatures: 0.1,
            glucides: 5,
            sucres: 1.9,
            proteines: 1.9,
        },
    },
    {
        name: "coing",
        months: ["Octobre"],
        kcal: 57,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 15.3,
            sucres: 6.3,
            proteines: 0.4,
        },
    },
    {
        name: "concombre",
        months: ["Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre"],
        kcal: 15,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 3.6,
            sucres: 1.7,
            proteines: 0.7,
        },
    },
    {
        name: "courge",
        months: ["Janvier", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 15,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 3.6,
            sucres: 1.7,
            proteines: 0.7,
        },
    },
    {
        name: "courgette",
        months: ["Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre"],
        kcal: 17,
        macros: {
            lipides: 0.3,
            acidesGrasSatures: 0,
            glucides: 3.1,
            sucres: 2.5,
            proteines: 1.2,
        },
    },
    {
        name: "cresson",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 11,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 1.3,
            sucres: 0.2,
            proteines: 2.3,
        },
    },
    {
        name: "endive",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Octobre"],
        kcal: 17,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 3.4,
            sucres: 0.3,
            proteines: 1.3,
        },
    },
    {
        name: "épinard",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 23,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0.1,
            glucides: 3.6,
            sucres: 0.4,
            proteines: 2.9,
        },
    },
    {
        name: "fenouil",
        months: ["Avril", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre"],
        kcal: 31,
        macros: {
            lipides: 0.2,
            acidesGrasSatures: 0,
            glucides: 7,
            sucres: 0,
            proteines: 1.2,
        },
    },
    {
        name: "figue",
        months: ["Juillet", "Août", "Septembre", "Octobre"],
        kcal: 74,
        macros: {
            lipides: 0.3,
            acidesGrasSatures: 0,
            glucides: 19.2,
            sucres: 16.3,
            proteines: 0.8,
        },
    },
    {
        name: "fruit de la passion",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 97,
        macros: {
            lipides: 0.7,
            acidesGrasSatures: 0.1,
            glucides: 23,
            sucres: 11,
            proteines: 2.2,
        },
    },
    {
        name: "haricot vert",
        months: ["Juin", "Juillet", "Août", "Septembre", "Octobre"],
        kcal: 31,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 7,
            sucres: 0,
            proteines: 1.8,
        },
    },
    {
        name: "kaki",
        months: ["Janvier", "Octobre", "Novembre", "Décembre"],
        kcal: 127,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0,
            glucides: 14.3,
            sucres: 13.9,
            proteines: 0.8,
        },
    },
    {
        name: "mâche",
        months: ["Janvier", "Février", "Octobre", "Novembre", "Décembre"],
        kcal: 21,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0,
            glucides: 3.6,
            sucres: 0,
            proteines: 2,
        },
    },
    {
        name: "mangue",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 60,
        macros: {
            lipides: 0.4,
            acidesGrasSatures: 0.1,
            glucides: 15,
            sucres: 14,
            proteines: 0.8,
        },
    },
    {
        name: "navet",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Octobre", "Novembre", "Décembre"],
        kcal: 28,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 6,
            sucres: 3.8,
            proteines: 0.9,
        },
    },
    {
        name: "oignon",
        months: ["Janvier", "Février", "Mars", "Avril", "Septembre", "Octobre", "Novembre", "Décembre"],
        kcal: 40,
        macros: {
            lipides: 0.1,
            acidesGrasSatures: 0,
            glucides: 9,
            sucres: 4.2,
            proteines: 1.1,
        },
    },
    {
        name: "panais",
        months: ["Janvier", "Février", "Mars", "Octobre", "Novembre", "Décembre"],
        kcal: 75,
        macros: {
            lipides: 0.3,
            acidesGrasSatures: 0.1,
            glucides: 18,
            sucres: 4.8,
            proteines: 1.2,
        },
    },
];
